
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('distillery_locations').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('distillery_locations').insert({id: 1, state: 'Alabama', abbr: 'AL', slug: 'alabama', country_code: 'US'}),
        knex('distillery_locations').insert({id: 2, state: 'Alaska', abbr: 'AK', slug: 'alaska', country_code: 'US'}),
        knex('distillery_locations').insert({id: 3, state: 'Arizona', abbr: 'AZ', slug: 'arizona', country_code: 'US'}),
        knex('distillery_locations').insert({id: 4, state: 'Arkansas', abbr: 'AR', slug: 'arkansas', country_code: 'US'}),
        knex('distillery_locations').insert({id: 5, state: 'California', abbr: 'CA', slug: 'california', country_code: 'US'}),
        knex('distillery_locations').insert({id: 6, state: 'Colorado', abbr: 'CO', slug: 'colorado', country_code: 'US'}),
        knex('distillery_locations').insert({id: 7, state: 'Connecticut', abbr: 'CT', slug: 'connecticut', country_code: 'US'}),
        knex('distillery_locations').insert({id: 8, state: 'Delaware', abbr: 'DE', slug: 'delaware', country_code: 'US'}),
        knex('distillery_locations').insert({id: 9, state: 'Florida', abbr: 'FL', slug: 'florida', country_code: 'US'}),
        knex('distillery_locations').insert({id: 10, state: 'Georgia', abbr: 'GA', slug: 'georgia', country_code: 'US'}),
        knex('distillery_locations').insert({id: 11, state: 'Hawaii', abbr: 'HI', slug: 'hawaii', country_code: 'US'}),
        knex('distillery_locations').insert({id: 12, state: 'Idaho', abbr: 'ID', slug: 'idaho', country_code: 'US'}),
        knex('distillery_locations').insert({id: 13, state: 'Illinois', abbr: 'IL', slug: 'illinois', country_code: 'US'}),
        knex('distillery_locations').insert({id: 14, state: 'Indiana', abbr: 'IN', slug: 'indiana', country_code: 'US'}),
        knex('distillery_locations').insert({id: 15, state: 'Iowa', abbr: 'IA', slug: 'iowa', country_code: 'US'}),
        knex('distillery_locations').insert({id: 16, state: 'Kansas', abbr: 'KS', slug: 'kansas', country_code: 'US'}),
        knex('distillery_locations').insert({id: 17, state: 'Kentucky', abbr: 'KY', slug: 'kentucky', country_code: 'US'}),
        knex('distillery_locations').insert({id: 18, state: 'Louisiana', abbr: 'LA', slug: 'louisiana', country_code: 'US'}),
        knex('distillery_locations').insert({id: 19, state: 'Maine', abbr: 'ME', slug: 'maine', country_code: 'US'}),
        knex('distillery_locations').insert({id: 20, state: 'Maryland', abbr: 'MD', slug: 'maryland', country_code: 'US'}),
        knex('distillery_locations').insert({id: 21, state: 'Massachusetts', abbr: 'MA', slug: 'massachusetts', country_code: 'US'}),
        knex('distillery_locations').insert({id: 22, state: 'Michigan', abbr: 'MI', slug: 'michigan', country_code: 'US'}),
        knex('distillery_locations').insert({id: 23, state: 'Minnesota', abbr: 'MN', slug: 'minnesota', country_code: 'US'}),
        knex('distillery_locations').insert({id: 24, state: 'Mississippi', abbr: 'MS'}),
        knex('distillery_locations').insert({id: 25, state: 'Missouri', abbr: 'MO', slug: 'missouri', country_code: 'US'}),
        knex('distillery_locations').insert({id: 26, state: 'Montana', abbr: 'MT', slug: 'montana', country_code: 'US'}),
        knex('distillery_locations').insert({id: 27, state: 'Nebraska', abbr: 'NE', slug: 'nebraska', country_code: 'US'}),
        knex('distillery_locations').insert({id: 28, state: 'Nevada', abbr: 'NV', slug: 'nevada', country_code: 'US'}),
        knex('distillery_locations').insert({id: 29, state: 'New Hampshire', abbr: 'NH', slug: 'new-hampshire', country_code: 'US'}),
        knex('distillery_locations').insert({id: 30, state: 'New Jersey', abbr: 'NJ', slug: 'new-jersey', country_code: 'US'}),
        knex('distillery_locations').insert({id: 31, state: 'New Mexico', abbr: 'NM', slug: 'new-mexico', country_code: 'US'}),
        knex('distillery_locations').insert({id: 32, state: 'New York', abbr: 'NY', slug: 'new-york', country_code: 'US'}),
        knex('distillery_locations').insert({id: 33, state: 'North Carolina', abbr: 'NC', slug: 'north-carolina', country_code: 'US'}),
        knex('distillery_locations').insert({id: 34, state: 'North Dakota', abbr: 'ND', slug: 'north-dakota', country_code: 'US'}),
        knex('distillery_locations').insert({id: 35, state: 'Ohio', abbr: 'OH', slug: 'ohio', country_code: 'US'}),
        knex('distillery_locations').insert({id: 36, state: 'Oklahoma', abbr: 'OK', slug: 'oklahoma', country_code: 'US'}),
        knex('distillery_locations').insert({id: 37, state: 'Oregon', abbr: 'OR', slug: 'Oregon', country_code: 'US'}),
        knex('distillery_locations').insert({id: 38, state: 'Pennsylvania', abbr: 'PA', slug: 'pennsylvania', country_code: 'US'}),
        knex('distillery_locations').insert({id: 39, state: 'Rhode Island', abbr: 'RI', slug: 'rhode-island', country_code: 'US'}),
        knex('distillery_locations').insert({id: 40, state: 'South Carolina', abbr: 'SC', slug: 'south-carolina', country_code: 'US'}),
        knex('distillery_locations').insert({id: 41, state: 'South Dakota', abbr: 'SD', slug: 'south-dakota', country_code: 'US'}),
        knex('distillery_locations').insert({id: 42, state: 'Tennessee', abbr: 'TN', slug: 'tennessee', country_code: 'US'}),
        knex('distillery_locations').insert({id: 43, state: 'Texas', abbr: 'TX', slug: 'texas', country_code: 'US'}),
        knex('distillery_locations').insert({id: 44, state: 'Utah', abbr: 'UT', slug: 'utah', country_code: 'US'}),
        knex('distillery_locations').insert({id: 45, state: 'Vermont', abbr: 'VT', slug: 'vermont', country_code: 'US'}),
        knex('distillery_locations').insert({id: 46, state: 'Virginia', abbr: 'VA', slug: 'virginia', country_code: 'US'}),
        knex('distillery_locations').insert({id: 47, state: 'Washington', abbr: 'WA', slug: 'washington', country_code: 'US'}),
        knex('distillery_locations').insert({id: 48, state: 'West Virginia', abbr: 'WV', slug: 'west-virginia', country_code: 'US'}),
        knex('distillery_locations').insert({id: 49, state: 'Wisconsin', abbr: 'WI', slug: 'wisconsin', country_code: 'US'}),
        knex('distillery_locations').insert({id: 50, state: 'Wyoming', abbr: 'WY', slug: 'wyoming', country_code: 'US'})
      ]);
    });
};
