
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('distilleries').del()
    .then(function () {
      return Promise.all([

        // COLORADO
        knex('distilleries').insert({
          id: 1,
          name: 'Leopold Bros',
          slug: 'leopold-bros',
          address: '4950 Nome St. Unit E',
          lat: 39.787223,
          lng: -104.851853,
          zip: 80239,
          email: 'sales@leopoldbros.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.leopoldbros.com',
          products: 'Brandy American, Small Batch Gin, Small Batch Vodka, Single Barrel Dark Rum, Rocky Mountain Blackberry, Peach Whiskey, Apple Whiskey, New York Sour Apple Liqueur, Rocky Mountain Blackberry, Three Pins Alpine, French Coffee, New England Cranberry, Maryland Style Rye Whiskey, Tennessee Style Whiskey',
          region: 'Denver',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 2,
          name: 'Stranahan\'s Colorado Whiskey',
          slug: 'stranahans-colorado-whiskey',
          address: '200 South Kalamath St',
          lat: 39.712539,
          lng: -104.99858,
          zip: 80223,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '303-296-7440',
          website: 'www.stranahans.com',
          products: 'Colorado Whiskey',
          region: 'Denver',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 3,
          name: 'Colorado Pure Distilling',
          slug: 'colorado-pure-distilling',
          address: '5609 West 6th Ave. Unit C',
          lat: 39.726238,
          lng: -105.058769,
          zip: 80214,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.coloradopuredistilling.com',
          products: 'Vodka',
          region: 'Denver',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 4,
          name: 'Mile High Spirits',
          slug: 'mile-high-spirits',
          address: '2201 Lawrence St',
          lat: 39.754540,
          lng: -104.989276,
          zip: 80205,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.drinkmhs.com',
          products: 'Whiskey',
          region: 'Denver',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 5,
          name: 'The Downslope Distilling Workshop',
          slug: 'the-downslope-distilling-workshop',
          address: '6770 S Dawson Circle Ste 400',
          lat: 39.594352,
          lng: -104.816847,
          zip:  80112,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.downslopedistilling.com',
          products: 'Vodka from Grain and Cane, Pepper Vodka, White Rum, Gold Rum, Vanilla Rum, Double Diamond Whiskey, Wine Barrel Aged Rum',
          region: 'Centennial',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 6,
          name: 'Roundhouse Spirits',
          slug: 'roundhouse-spirits',
          address: '5311 Western Ave',
          lat: 40.017858,
          lng: -105.22939,
          zip:  80301,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.vapordistillery.com',
          products: 'Roundhouse Gin, Roundhouse coffee liqueur',
          region: 'Boulder',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 7,
          name: 'Boulder Distillery & Clear Spirits Co.',
          slug: 'boulder-distillery-and-clear-spirits-co',
          address: '2500 47th St. Suite 10',
          lat: 40.025696,
          lng: -105.243337,
          zip:  80301,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.303vokda.com',
          products: '303 Vodka',
          region: 'Boulder',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 8,
          name: 'Riverfront Distillery',
          slug: 'riverfront-distillery',
          address: '644 Bluebird Ave',
          lat: 40.106228,
          lng: -105.202482,
          zip:  80503,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.303vokda.com',
          products: 'Whiskey',
          region: 'Niwot',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 9,
          name: 'Tesouro Distillery',
          slug: 'tesouro-distillery',
          address: '105 S Sunset St',
          lat: 40.157381,
          lng: -105.122166,
          zip:  80501,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.tesourodistillery.com',
          products: 'Wine-barrel aged rum',
          region: 'Longmont',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 10,
          name: 'Black Canyon Distillery',
          slug: 'black-canyon-distillery',
          address: '1371O Deere Court',
          lat: 40.201842,
          lng: -104.972005,
          zip:  80504,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.blackcanyondistillery.com',
          products: 'Black Canyon Whiskey',
          region: 'Longmont',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 11,
          name: 'Syntax Spirits',
          slug: 'syntax-spirits',
          address: '625 3rd St',
          lat: 40.431469,
          lng: -104.688292,
          zip:  80631,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.syntaxspirits.com',
          products: 'Vodka',
          region: 'Greeley',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 12,
          name: 'Dancing Pines Distillery',
          slug: 'dancing-pines-distillery',
          address: '1527 Taurus Ct',
          lat: 40.431469,
          lng: -104.688292,
          zip:  80537,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.dancingpinesdistillery.com',
          products: 'Whiskey',
          region: 'Loveland',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 13,
          name: 'Spring 44 Distilling',
          slug: 'spring-44-distlling',
          slug: 'spring-44',
          address: '505 W 6th Ave',
          lat: 40.397569,
          lng: -105.082233,
          zip:  80537,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.spring44.com',
          products: 'Whiskey',
          region: 'Loveland',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 14,
          name: 'Feisty Spirits Distillery',
          slug: 'feisty-spirits-distillery',
          address: '1708 East Lincoln Ave',
          lat: 40.584972,
          lng: -105.046055,
          zip:  80524,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.feistyspirits.com',
          products: 'Rye whiskey, Oat whiskey, Millet whiskey, Kamut whiskey, Bourbon',
          region: 'Fort Collins',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 15,
          name: 'Front Range Distilling',
          slug: 'front-range-distilling',
          address: '305 Park St',
          lat: 40.584972,
          lng: -105.046055,
          zip:  80521,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.frdistilling.com',
          products: 'Whiskey',
          region: 'Fort Collins',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 16,
          name: 'Mystic Mountain Distillery',
          slug: 'mystic-mountain-distillery',
          address: '11505 Spring Valley Rd',
          lat: 39.197228,
          lng: -104.774122,
          zip:  80118,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.mysticmtspirists.com',
          products: 'Colorado Blue Vodka, Colorado Crystal Vodka, BOHICA Vodka, Rocky Mountain Moonshine, Blackjack Bourbon Whiskey, Colorado Fog Gin, Blackbeard Rums',
          region: 'Larkspur',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 17,
          name: 'Distillery 291',
          slug: 'distillery-291',
          address: '1647 S Tejon St',
          lat: 39.197228,
          lng: -104.774122,
          zip:  80905,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.distillery291.com',
          products: 'Whiskey',
          region: 'Colorado Springs',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 18,
          name: 'Wood\'s High Mountain Distillery',
          slug: 'woods-hight-mountain-distillery',
          address: '44 W 1st St',
          lat: 38.536018,
          lng: -105.991845,
          zip:  81201,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.woodsdistillery.com',
          products: 'Whiskey',
          region: 'Salida',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 19,
          name: 'Boathouse Distillery',
          slug: 'boathouse-distillery',
          address: '6573 Ridge Rd',
          lat: 38.51532,
          lng: -105.994742,
          zip:  81201,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.boathousedistillery.com',
          products: 'Whiskey',
          region: 'Salida',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 20,
          name: 'Deerhammer Distillers',
          slug: 'deerhamme-distillers',
          address: '321 East Main St',
          lat: 38.842352,
          lng: -106.129882,
          zip:  81211,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.deerhammer.com',
          products: 'Breckenridge Vodka, Breck Bourbon, Single Malt Whiskey, Dark Rum, Alpine Liquer, Infused Vodkas, Bitters, White Dog, Winter Schnapps',
          region: 'Buena Vista',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 21,
          name: 'Double Diamond Distillery',
          slug: 'double-diamond-distillery',
          address: '400 N. Park Ave',
          lat: 39.488844,
          lng: -106.046991,
          zip:  80424,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.doublediamonddistillery.com',
          products: 'Whiskey',
          region: 'Breckenridge',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 22,
          name: 'Breckenridge Distillery',
          slug: 'breckenridge-distillery',
          address: '1925 Airport Rd',
          lat: 39.509409,
          lng: -106.051819,
          zip:  80424,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.breckenridgedistillery.com',
          products: 'Breckenridge Vodka, Breck Bourbon, Single Malt Whiskey, Dark Rum, Alpine Liquer, Infused Vodkas, Bitters, White Dog, Winter Schnapps',
          region: 'Breckenridge',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 23,
          name: 'Woody Creek Distillers',
          slug: 'woody-creek-distillers',
          address: '60 Sunset Dr',
          lat: 39.37306,
          lng: -107.0805,
          zip:  81621,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.woodycreekdistillers.com',
          products: 'Vodka, Gin, Whiskey, Bourbon',
          region: 'Basalt',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 24,
          name: 'Peak Spirits',
          slug: 'peak-spirits',
          address: '26567 North Rd',
          lat: 38.797882,
          lng: -107.72378,
          zip:  81419,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.peakspirits.com',
          products: 'Brandy, Caprock Organic Gin, Vodka, Peak Organic Eau De Vie',
          region: 'Hotchkiss',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 25,
          name: 'Colorado Gold Distillery',
          slug: 'colorado-gold-distillery',
          address: '1290 S Grand Mesa Dr',
          lat: 38.887412,
          lng: -107.930996,
          zip:  81413,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.coloradogolddistillers.com',
          products: 'Whiskey, Agave Spirits Tequila, Brandy',
          region: 'Cedaredge',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),
        knex('distilleries').insert({
          id: 26,
          name: 'Peach Street Distillers',
          slug: 'peach-street-distillers',
          address: '144 South Kluge St',
          lat: 39.111036,
          lng: -108.352575,
          zip:  81526,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.peachstreetdistillers.com',
          products: 'Brandy ack, Jenny Pear, Peach and Plum Brandies, Bourbon',
          region: 'Palisade',
          hood: 'dtwn',
          state: 'CO',
          state_full: 'Colorado'
        }),

        //NEW MEXICO
        knex('distilleries').insert({
          id: 27,
          name: 'Santa Fe Spirits',
          slug: 'santa-fe-spririts',
          address: '7505 Mallard Way',
          lat: 35.635849,
          lng: -106.065381,
          zip:  87507,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.santafespirits.com',
          products: 'Whiskey, Apple Brandy, Unaged Whiskey, Eau De Vie',
          region: 'Santa Fe',
          hood: 'dtwn',
          state: 'NM',
          state_full: 'New-Mexico'
        }),
        knex('distilleries').insert({
          id: 28,
          name: 'Don Quixote Distillery',
          slug: 'don-quixote-distillery',
          address: '236 Rio Bravo',
          lat: 35.801216,
          lng: -106.205885,
          zip:  87544,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.dqdistillery.com',
          products: 'Blue Corn Vodka, Brandy',
          region: 'Los Alamos',
          hood: 'dtwn',
          state: 'NM',
          state_full: 'New-Mexico'
        }),

        //UTAH
        knex('distilleries').insert({
          id: 29,
          name: 'High West Distlllery',
          slug: 'high-west-distillery',
          address: '703 Park Ave',
          lat: 40.646412,
          lng: -111.498249,
          zip:  84060,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.highwest.com',
          products: 'Rendezvous Rye Whiskey, Rocky Mountain Rye, Vodka 7000, Oak Whiskey, Peach Whiskey',
          region: 'Park City',
          hood: 'dtwn',
          state: 'UT',
          state_full: 'Utah'
        }),
        knex('distilleries').insert({
          id: 30,
          name: 'Ogden\'s Own Distillery',
          slug: 'ogdens-own-distillery',
          address: '2679 Midland Dr',
          lat: 41.216858,
          lng: -112.009456,
          zip:  84401,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.ogdensenown.com',
          products: 'Herbal Liqueur, Rum, Gin',
          region: 'Odgen',
          hood: 'dtwn',
          state: 'UT',
          state_full: 'Utah'
        }),

        //ARIZONA
        knex('distilleries').insert({
          id: 31,
          name: 'Hamilton Distillers',
          slug: 'hamilton-distillers',
          address: '209 N. Hoff Ave',
          lat: 32.224024,
          lng: -110.964875,
          zip:  85705,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.hamiltondistillers.com',
          products: 'Whiskey made with a copper pot still',
          region: 'Tucson',
          hood: 'dtwn',
          state: 'AZ',
          state_full: 'Arizona'
        }),
        knex('distilleries').insert({
          id: 32,
          name: 'Tombstone Spirits',
          slug: 'tombstone-spirits',
          address: '25 W Southern Ave',
          lat: 32.224024,
          lng: -110.964875,
          zip:  85282,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.azcraftbev.com',
          products: 'Whiskey',
          region: 'Tempe',
          hood: 'dtwn',
          state: 'AZ',
          state_full: 'Arizona'
        }),
        knex('distilleries').insert({
          id: 33,
          name: 'Forward Brands',
          slug: 'forward-brands',
          address: '3517 E. Monterosa St',
          lat: 33.495691,
          lng: -112.006345,
          zip:  85018,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.forwardbrands.com',
          products: 'Arroyo Vodka, BB\'s Apple Pye',
          region: 'Phoenix',
          hood: 'dtwn',
          state: 'AZ',
          state_full: 'Arizona'
        }),
        knex('distilleries').insert({
          id: 34,
          name: 'Desert Diamond Distillery',
          slug: 'desert-diamond-distillery',
          address: '4875 Olympic Dr',
          lat: 35.258608,
          lng: -113.950582,
          zip:  86401,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.desertdiamonddistillery.com',
          products: 'Gold Miner Rum, Gold Miner Dark Rum, Gold Miner Agave Rum, Gold Miner Vodka',
          region: 'Kingman',
          hood: 'dtwn',
          state: 'AZ',
          state_full: 'Arizona'
        }),

        //NEVADA
        knex('distilleries').insert({
          id: 35,
          name: 'Las Vegas Distillery',
          slug: 'las-vegas-distillery',
          address: '7330 Eastgrate Rd',
          lat: 36.054099,
          lng: -115.01986,
          zip:  89011,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.desertdiamonddistillery.com',
          products: ' Vodka, gin, rum, Whiskey, Bourbon, grappa fruit distillates, old-fashed fruit distillates',
          region: 'Henderson',
          hood: 'dtwn',
          state: 'NV',
          state_full: 'Nevada'
        }),
        knex('distilleries').insert({
          id: 36,
          name: 'Las Vegas Distillery',
          slug: 'las-vegas-distillery',
          address: '7330 Eastgrate Rd',
          lat: 36.054099,
          lng: -115.01986,
          zip:  89011,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.lasvegasdistillery.com',
          products: ' Vodka, gin, rum, Whiskey, Bourbon, grappa fruit distillates, old-fashed fruit distillates',
          region: 'Henderson',
          hood: 'dtwn',
          state: 'NV',
          state_full: 'Nevada'
        }),
        knex('distilleries').insert({
          id: 37,
          name: 'Copper Angels Distilling',
          slug: 'copper-angels-distilling',
          address: '1350 Horizon Ridge Pkwy',
          lat: 36.023405,
          lng: -115.046875,
          zip:  89012,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.lasvegasdistillery.com',
          products: ' Vodka, gin, rum, Whiskey, Bourbon, grappa fruit distillates, old-fashed fruit distillates',
          region: 'Henderson',
          hood: 'dtwn',
          state: 'NV',
          state_full: 'Nevada'
        }),
        knex('distilleries').insert({
          id: 38,
          name: 'Red Shoes Distillery',
          slug: 'red-shoes-distillery',
          address: '8550 W Desert Inn Rd',
          lat: 36.13138,
          lng: -115.277975,
          zip:  89117,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.lasvegasdistillery.com',
          products: 'Vodka',
          region: 'Las Vegas',
          hood: 'dtwn',
          state: 'NV',
          state_full: 'Nevada'
        }),
        knex('distilleries').insert({
          id: 39,
          name: 'Churchill Vineyards & Distillery',
          slug: 'churchill-vineyards-and-distillery',
          address: '1045 Dodge Ln',
          lat: 39.368714,
          lng: -118.759696,
          zip:  89406,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.churchillvineyards.com',
          products: 'Brandy, Grappa, Vodka',
          region: 'Fallon',
          hood: 'dtwn',
          state: 'NV',
          state_full: 'Nevada'
        }),
        knex('distilleries').insert({
          id: 40,
          name: 'High Sierra Spirits',
          slug: 'high-sierra-spirits',
          address: '564 Silvertip Dr',
          lat: 39.252465,
          lng: -119.980981,
          zip:  89451,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.highsierraspirits.com',
          products: 'Whiskey',
          region: 'Incline Village',
          hood: 'dtwn',
          state: 'NV',
          state_full: 'Nevada'
        }),

        //CALIFORNIA
        knex('distilleries').insert({
          id: 41,
          name: 'Kill Devil Spirit Co',
          slug: 'kill-devil-spirit-co',
          address: '2766 Via Orange Way',
          lat: 32.728217,
          lng: -116.968324,
          zip:  91978,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.ardistillery.com',
          products: 'White Whiskey',
          region: 'San Diego',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 42,
          name: 'Ballast Point Spirits',
          slug: 'ballast-point-spirits',
          address: '10051 Old Grove Rd',
          lat: 32.898385,
          lng: -117.11091,
          zip:  92131,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.ballastpoint.com',
          products: 'Whiskey, Rum, Gin',
          region: 'San Diego',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 43,
          name: 'Desert Distilling',
          slug: 'desert-distilling',
          address: '34300 Gateway Dr',
          lat: 33.797859,
          lng: -116.383238,
          zip:  92211,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.desertdistilling.com',
          products: 'Vodka, Lemon Flavored Vodka, Lime Flavored Vodka, Orange Flavored Vodka, White Rum, Aged Rum',
          region: 'Palm Desert',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 44,
          name: 'Skyrocket Distillers',
          slug: 'skyrocket-distillers',
          address: '27315 Jafferson Ave',
          lat: 33.521384,
          lng: -117.166421,
          zip:  92590,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.skyrocketdistillers.com',
          products: 'Blue Agave Spirits',
          region: 'Temecula',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 45,
          name: 'Bear & Eagle Products',
          slug: 'bear-and-eagle-products',
          address: '1425 E Borchard St',
          lat: 33.728145,
          lng: -117.851264,
          zip:  92705,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.beareagle.com',
          products: 'Vodka, Arak, Brandy',
          region: 'Santa Ana',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 46,
          name: 'St. James Spirits',
          slug: 'st-james-spirits',
          address: '5220 Fourth St',
          lat: 34.108131,
          lng: -117.937911,
          zip:  91701,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.saintjamesspirits.com',
          products: 'Peregrine Rock Single Malt Whiskey, Royal Hawaiian Pineapple Rum and Brandy, California Gold Agave, Raspberry Regal Wine',
          region: 'Irvingdale',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 47,
          name: 'Stark Spirits',
          slug: 'stark-spirits',
          address: '1260 Lincoln Ave',
          lat: 34.168658,
          lng: -118.158667,
          zip:  91103,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.starkspirits.com',
          products: 'Whiskey, Rum',
          region: 'Pasadena',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 48,
          name: 'Greenbar Collective',
          slug: 'greenbar-collective',
          address: '2459 E 8th St',
          lat: 34.029727,
          lng: -118.228126,
          zip:  90021,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.greenbar.biz',
          products: 'Bar Keep bitters, Crusoe rum, Fruitlab liqueur, Grand Poppy Liqueur, Ixa tequila, Slow Hand whiskey, Tru gin, Tru vodka',
          region: 'Los Angeles',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 49,
          name: 'Cutler\'s Artisan Spirits',
          slug: 'cutlers-artisan-spirits',
          address: '137 Anacapa St',
          lat: 34.414597,
          lng: -119.690638,
          zip:  93101,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.cutlersartisan.com',
          products: 'Whiskey',
          region: 'Santa Barbara',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 50,
          name: 'Lloyd Distillery',
          slug: 'lloyd-distillery',
          address: '469 Pacific St',
          lat: 35.275058,
          lng: -120.665975,
          zip:  93401,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.localmicrodistillers.com',
          products: 'Whiskey',
          region: 'San Luis Obispo',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 51,
          name: 'Marian Farms',
          slug: 'marian-farms',
          address: '2305 Rolinda Ave',
          lat: 36.770023,
          lng: -119.963171,
          zip:  93722,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.marianfarmsbiodynamic.com',
          products: 'California Style Pisco, Espirito Biodynamic Brandy, Farmhouse Vodka, Farmhouse Curacao',
          region: 'Fresno',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 52,
          name: 'Fog\'s End Distillery',
          slug: 'fogs-end-distillery',
          address: '342 Capitol St',
          lat: 36.671366,
          lng: -121.659915,
          zip:  93901,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.fogsenddistillery.com',
          products: 'Moonshine, Whiskey',
          region: 'Salinas',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 53,
          name: 'Osocalis Distillery',
          slug: 'osocalis-distillery',
          address: '5579 Old San Jose Rd',
          lat: 37.05739,
          lng: -121.945152,
          zip:  95073,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.osocalis.com',
          products: 'Rare Alambic Brandy, XO Alambic Brandy, Apple Brandy, Heritage Blend Brandy',
          region: 'Soquel',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 54,
          name: 'Valley Spirits',
          slug: 'valley-spirits',
          address: '553 Mariposa Rd',
          lat: 37.63276,
          lng: -120.934453,
          zip:  95354,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.drinkvalleyspirits.com',
          products: 'Whiskey, Vodka, Moonshine from grain',
          region: 'Modesto',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 55,
          name: 'Brandymaking & Spirits',
          slug: 'brandymaking-and-spirits',
          address: '600 Yosemite Blvd',
          lat: 37.634052,
          lng: -120.980608,
          zip:  95354,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.gallo.com',
          products: 'Brandy',
          region: 'Modesto',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 56,
          name: 'Essential Spirits',
          slug: 'essential-spirits',
          address: '144-A South Whisman Rd',
          lat: 37.387127,
          lng: -122.064028,
          zip:  94041,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.essentialspirits.com',
          products: 'Sgt Classick Gold and Silver Hawaiian Rums, PurePear Brandy, Classick Grappadi Cabernet, Classick Original American Bierschnaps, DH Krahn Gin, U4RIK Vodka',
          region: 'Mountain View',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 57,
          name: 'Old World Spirits',
          slug: 'old-world-spirits',
          address: '121 Industrial Rd',
          lat: 37.521065,
          lng: -122.265644,
          zip:  94002,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.oldworldspirits.com',
          products: ' Blade Gin, Rusty Blade Barrel Aged Gin, Poire Williams, O\'Henry Barrel Aged Peach Eau-De-Vie, Indian Blood Peach Eau-De-Vie, Kuchan Black Walnut Liqueur, La Sorciere Absinthe Verte,. Kuchan Alambic Brandy, Rye Whiskey, Rum',
          region: 'Belmont',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 58,
          name: 'St. George Spirits',
          slug: 'st-george-spirits',
          address: '2601 Monarch St',
          lat: 37.787441,
          lng: -122.309268,
          zip:  94501,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.stgeorgespirits.com',
          products: 'St George Single Malt Whiskey, St George Absinthe Verte, St George Botanivore, Terroir, Dry Rye Gin, Agua Libre Rum, Aqua Perfecta Eaux de Vie, Breaking & Entering Bourbon, Hangar One Vodka, Firelit Coffee Liqueur, Qi Tea Liqueurs',
          region: 'Alameda',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 59,
          name: 'Distillery 209',
          slug: 'distillery-209',
          address: 'Pier 50, Shed B',
          lat: 37.774772,
          lng: -122.387223,
          zip:  94158,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.distillery209.com',
          products: 'Gin',
          region: 'San Francisco',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 60,
          name: 'Anchor Brewers & Distillers',
          slug: 'anchor-brewers-and-distillers',
          address: '1705 Mariposa St',
          lat: 37.763086,
          lng: -122.401085,
          zip:  94107,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.anchorbrewing.com',
          products: 'Old Potrero 18th Century Style Whiskey, Old Potrero Straight Rye Whiskey, Old Potrero Hotalings Whiskey, Junipero Gin, Genevieve Gin',
          region: 'San Francisco',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 61,
          name: 'Falcon Spirits',
          slug: 'falcon-spirits',
          address: '3701 Collins Ave',
          lat: 37.981538,
          lng: -122.353384,
          zip:  94806,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.falconspirits.com',
          products: 'Rum',
          region: 'Richmond',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 62,
          name: 'Dry Diggings Distillery',
          slug: 'dry-diggings-distillery',
          address: '5050 Robert J Mathews Pkwy',
          lat:  38.622558,
          lng: -121.059251,
          zip:  95762,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.drydiggingsdistillery.com',
          products: 'Whiskey',
          region: 'El Dorado Hills',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 63,
          name: 'Tahoe Moonshine',
          slug: 'tahoe-moonshine',
          address: '1611 Shop St',
          lat:  38.902994,
          lng: -120.012524,
          zip:  96150,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.tahoemoonshine.com',
          products: 'Rum, Gin, Absinthe ,Vodka, Fruit Brandy',
          region: 'Lake Tahoe',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 64,
          name: 'Hawj Brothers Distillery',
          slug: 'hawj-brothers-distillery',
          address: '1100 Garden Hwy',
          lat:  39.111086,
          lng: -121.616635,
          zip:  95991,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.tahoemoonshine.com',
          products: 'Baijiu, Soju, Vodka, Bourbon',
          region: 'Yuba City',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 65,
          name: 'Jaxon Keys Distillery',
          slug: 'jaxon-keys-distillery',
          address: '10400 S Hwy 101',
          lat:  39.012986,
          lng: -123.128114,
          zip:  95449,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.jacksonkeys.com',
          products: 'Brandy',
          region: 'Hopland',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 66,
          name: 'Greenway Distillers',
          slug: 'greenway-distillers',
          address: '5000 Low Gap Rd',
          lat:  39.165293,
          lng: -123.274391,
          zip:  95482,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.greenwaydistillers.com',
          products: 'Germain-Robin Absinthe Superiure, Crispin\'s Rose Liqueur',
          region: 'Ukiah',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 67,
          name: 'Solomon Tournour Co',
          slug: 'solomon-tournour-co',
          address: '5900 Central Ave',
          lat:  39.229199,
          lng: -123.210146,
          zip:  95418,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.solomontournourdistillery.com',
          products: 'Pear Eau De Vie, Fruit Brandy',
          region: 'Calpella',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 68,
          name: 'Germain-Robin',
          slug: 'germain-robin',
          address: '1110 Bel Arbres Dr',
          lat:  39.257018,
          lng: -123.237612,
          zip:  95470,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.craftdistillers.com',
          products: 'Select Barrel XO, Single Barrel Pinot Noir, Colombard grape brandies, Anno Domini, Coast Road Reserve, Craft Method Brandy',
          region: 'Redwood Valley',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),
        knex('distilleries').insert({
          id: 69,
          name: 'Germain-Robin',
          slug: 'germain-robin',
          address: '1110 Bel Arbres Dr',
          lat:  39.257018,
          lng: -123.237612,
          zip:  95470,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.craftdistillers.com',
          products: 'Select Barrel XO, Single Barrel Pinot Noir, Colombard grape brandies, Anno Domini, Coast Road Reserve, Craft Method Brandy',
          region: 'Redwood Valley',
          hood: 'dtwn',
          state: 'CA',
          state_full: 'California'
        }),

        //OREGON

        knex('distilleries').insert({
          id: 70,
          name: 'Immortal Spirits',
          slug: 'immortal-spirits',
          address: '3582 S Pacfic Hwy',
          lat:  42.285996,
          lng: -122.833328,
          zip:  97501,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.immortalspirits.com',
          products: 'Brandy, Whiskey, Rum, Absinthe, Brandy',
          region: 'Medford',
          hood: 'dtwn',
          state: 'OR',
          state_full: 'Oregon'
        }),
        knex('distilleries').insert({
          id: 71,
          name: 'Brandy Peak Distillery',
          slug: 'brandy-peak-distillery',
          address: '18526 Tetley Rd',
          lat:  42.113477,
          lng: -124.30305,
          zip:  97415,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.brandypeak.com',
          products: 'Brandy, Grappa, Pear E De Vie, Blackberry Liqueur',
          region: 'Brookings',
          hood: 'dtwn',
          state: 'OR',
          state_full: 'Oregon'
        }),
        knex('distilleries').insert({
          id: 72,
          name: 'Bendistillery Inc',
          slug: 'bendistillery-inc',
          address: '19330 Pinehurst Rd',
          lat:  44.158921,
          lng: -121.355817,
          zip:  97701,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.bendistillery.com',
          products: 'Crater Lake Vodka, Cascade Mountain Gin, Cofia Hazelnut Espresso Vodka, Mazama Infused Pepper Vodka, Diamond 100 Vodka',
          region: 'Bend',
          hood: 'dtwn',
          state: 'OR',
          state_full: 'Oregon'
        }),
        knex('distilleries').insert({
          id: 73,
          name: 'Oregon Spirit Distillers',
          slug: 'oregon-spirit-distillers',
          address: '490 Butler Market Rd',
          lat:  44.078063,
          lng: -121.298654,
          zip:  97701,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'wwww.oregonspiritdistillers.com',
          products: 'Oregon Spirit Vodka, Black Mariah Cordial Merrylegs Gin',
          region: 'Bend',
          hood: 'dtwn',
          state: 'OR',
          state_full: 'Oregon'
        }),
        knex('distilleries').insert({
          id: 74,
          name: 'Rogue House of Spirits',
          slug: 'rogue-house-of-spirits',
          address: '2320 SE Osu Dr',
          lat:  44.61991,
          lng: -124.052339,
          zip:  97365,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.roguespirits.com',
          products: 'Rum, Whiskey, Gin',
          region: 'Newport',
          hood: 'dtwn',
          state: 'OR',
          state_full: 'Oregon'
        }),
        knex('distilleries').insert({
          id: 75,
          name: 'Ransom Spirits',
          slug: 'ransom-spirits',
          address: '23101 Houser Rd',
          lat:  45.093659,
          lng: -123.464313,
          zip:  97378,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.ransomspirits.com',
          products: 'Whiskey, Vodka, Grappa, Gin',
          region: 'Sheridan',
          hood: 'dtwn',
          state: 'OR',
          state_full: 'Oregon'
        }),
        knex('distilleries').insert({
          id: 76,
          name: 'Sub Rosa',
          slug: 'sub-rosa',
          address: '876 SW Alder Dr',
          lat:  45.27865,
          lng: -123.017156,
          zip:  97115,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.subrosaspirits.com',
          products: 'Tarragon Infused Vodka, Saffron Infused Vodka',
          region: 'Dundee',
          hood: 'dtwn',
          state: 'OR',
          state_full: 'Oregon'
        }),
        knex('distilleries').insert({
          id: 77,
          name: 'Indio Spirits',
          slug: 'indio-spirits',
          address: '7272 SW Durham Rd',
          lat:  45.400804,
          lng: -122.751982,
          zip:  97224,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.indiospirits.com',
          products: 'Tarragon Infused Vodka, Saffron Infused Vodka',
          region: 'Portland',
          hood: 'dtwn',
          state: 'OR',
          state_full: 'Oregon'
        }),
        knex('distilleries').insert({
          id: 78,
          name: 'Stone Barn Brandy Works',
          slug: 'stone-barn-brandy-works',
          address: '3315 SE 19th St',
          lat:  45.498816,
          lng: -122.646925,
          zip:  97202,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.stonebarnbrandsworks.com',
          products: 'Pear Brandy, Apple Brandy, Grappa, Ouzo, Rye Spirits, Coffee Liqueur',
          region: 'Portland',
          hood: 'dtwn',
          state: 'OR',
          state_full: 'Oregon'
        }),
        knex('distilleries').insert({
          id: 79,
          name: 'Clear Creek Distilling',
          slug: 'clear-creek-distilling',
          address: '2389 NW Wilson St',
          lat:  45.537756,
          lng: -122.700591,
          zip:  97210,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.clearcreekdistillery.com',
          products: 'Williams Pear, Barrel Aged Eau De Vie, Oregon Single Malt Whiskey, Brandy',
          region: 'Portland',
          hood: 'dtwn',
          state: 'OR',
          state_full: 'Oregon'
        }),
        knex('distilleries').insert({
          id: 80,
          name: 'McMenamins Edgefield Distillery',
          slug: 'mcmenamins-edgefield-distillery',
          address: '2126 S.W. Halsey St',
          lat:  45.53702,
          lng: -122.406406,
          zip:  97060,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.mcmenamins.com',
          products: 'Whiskey, Vintners American Distilled Gin, Brandy',
          region: 'Troutdale',
          hood: 'dtwn',
          state: 'OR',
          state_full: 'Oregon'
        }),
        knex('distilleries').insert({
          id: 81,
          name: 'Northwest Distillery',
          slug: 'northwest-distillery',
          address: '32914 Church Rd',
          lat:  45.818291,
          lng: -122.889934,
          zip:  97053,
          email: 'example@mail.com',
          picture: 'distill-placeholder.png',
          phone: '555-555-5555',
          website: 'www.nwdistillery.com',
          products: 'Liquid Vodka, Mint flavored vodka',
          region: 'Warren',
          hood: 'dtwn',
          state: 'OR',
          state_full: 'Oregon'
        }),

        //WASHINGTON
      ]);
    });
};
